services:
  portainer:
    image: portainer/portainer-ce:2.33.7
    container_name: portainer
    restart: unless-stopped
    user: "1203:1203"
    ports:
      - "8999:9000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
    networks:
      - portainer_network

volumes:
  portainer_data:

networks:
  portainer_network:
